### PR TITLE
Allow using variable names inside src attributes

### PR DESCRIPTION
**Pull request by qparis**

### CODE REVIEW

**Comment by qparis** [comment]
Thank you for merging.
Is it possible to release a new version of the npm artifact? 

Many thanks

**Comment by BenzLeung** [comment]
@qparis done.
Ver. 0.4.7

**Comment by qparis** [comment]
Thanks, but another difference included in 0.4.7 prevents parcel from starting.

```
 Cannot read property 'forEach' of undefined
 at HbsAsset.parse (/Users/*/Documents/Developement/**/node_modules/parcel-plugin-handlebars-benz/lib/HbsAsset.js:41:22)
at HbsAsset.parseIfNeeded (/Users/qparis/Documents/Developement/**node_modules/parcel-bundler/src/Asset.js:60:29)
```

 After investigation, there is another difference in utils.js which seems to be the cause of the problem. I've made another merge request 
capture d ecran 2018-09-06 a 14 47 51

I've made another merge request (#2), but I'm not 100% that it has no side effects. Can you help me? Thanks

**Comment by BenzLeung** [comment]
I'm sorry I uploaded v0.4.6 to npm but forgot to commit to github.
#2 merged and uploaded to npm (v0.4.8). Thanks for your request.

**Pull request merged**
